FROM debian:stretch
RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install boto3 
RUN pip3 install botocore 
RUN pip3 install python-dateutil
RUN pip3 install pex
